---
version: '3.8'
services:
  movies:
    image: siddharth2087/moviesrepo:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: siddharth2087/trainrepo:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: siddharth2087/dthrepo:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: siddharth2087/rechargerepo:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

